name: 'Notify Failed Workflow Action'
description:
  'This action sends a notification to a email address and a slack channel when
  a workflow fails.'
author: 'aialok'

# Define your inputs here.
inputs:
  sender_email:
    description: 'Email address to send message on behalf of.'
    required: true
  sender_email_password:
    description: 'SMTP password for the email address of sender.'
    required: true
  team_email_addresses:
    description: 'Email addresses for team notifications.'
    required: true
  slack_webhook:
    description: 'Slack webhook URL to send the notification to.'
    required: false
  github_token:
    description: 'GitHub token to access the repository.'
    required: true
# Define your outputs here.
outputs:
  status:
    description: 'Status of the notification.'
    value: ${{ steps.notify.outputs.status }}

runs:
  using: node20
  main: dist/index.js
